language: php
dist: bionic
php:
  - 8.3
  - 8.4

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - vendor

before_install:
  - composer self-update

install:
  - composer install -o --prefer-dist --no-interaction

script:
  - composer test
